### ISSUE TITLE
"kia_subtitle" meta_key not saving on the database

### ISSUE THREAD

**Issue by livecommunitychile** [helgatheviking/KIA-Subtitle#16]
Hi, we're trying to use this plugin.

For some reason when we change the value of the Subtitle on the WP Editor it doesn't save on the database

We tried to put manually the "kia_subtitle" meta_key on our post and it works! For some reason the meta isn't saving. 

We're using the plugin for Blog Entries. 

Is there a way to fix this?

Thank you!

**Comment by helgatheviking** [comment]
Are you referring to the Block editor sidebar? Or the classic editor? Typical debugging advice would be trying to isolate this issue... can you reproduce it with no other plugins enabled and a default theme? If not, you may have a conflict with another bit of code. Even a Javascript error in the block editor would probably break functionality since the whole editor is Javascript-based.
