### ISSUE TITLE
limit a characters quantity (Add content validation filters for save routine)

### ISSUE THREAD

**Issue by alessandragiacon** [helgatheviking/KIA-Subtitle#17]
I need limit the quantity of characters in KIA subtitle and i haven't found nothing for help me.

**Comment by helgatheviking** [comment]
Hi there. That's not a feature I have in the plugin... and I probably won't add it. What could happen is I could add a filter [here](https://github.com/helgatheviking/KIA-Subtitle/blob/master/kia-subtitle.php#L521) so that you can modify the string actually going in to the DB. 

You'd have to then write your own code to enforce the limitation.
