### ISSUE TITLE
Error regarding KIA subtitle

### ISSUE THREAD

**Issue by Mathib96** [helgatheviking/KIA-Subtitle#7]
Hi :)
I have now implented the KIA subtitle plugin - what a great plugin i must say!

When that is said i have a question or two.

1. Firstly it doesnt seem, at the woocommerce ordre-page, to include the subtitle for the ordered products... Is that something that could be fixed, or do you have any idea how to solve it, since i now can't see the products people are ordering.

2. At the confirmation email, to the customers, they cannot see the subtitle either for the ordered products. do i need to edit the email structure, or? and how?

3. When a customer log in at my website, to see there order, and they are going to show the order, they can't see the subtitle for the product either?

Have a great day.

Best regards
//Mathias Brask
mb@bravocom.dk

**Comment by helgatheviking** [comment]
Hi Mathias,

This is not an error. The plugin is purely for adding a quick admin UI for saving a subtitle to each page. By design, the plugin doesn't attempt to *display* any subtitles on the front-end. Since every theme is different this would be a support disaster for me. I could possibly filter `the_title()`, but then I'd be forcing bad markup on everyone. It is up to you to add the subtitle to your theme where you'd like it, see the [faq](https://github.com/helgatheviking/KIA-Subtitle#frequently-asked-questions) for reference. 

One day, I might consider making a KIA Subtitle Pro that integrates with WooCommerce, but not right now. I don't provide support for this level of customization. If you wanted to hire me to integrate the subtitle into the cart/checkout/email/myaccount aspects of WooCommerce, I would be open to that.

**Comment by Mathib96** [comment]
Could you let me know the price estimate? :-)

**Comment by helgatheviking** [comment]
@Mathib96 this got a little lost in my recent travel and I'm not at WordCamp US. I will try to get you a quote on Monday.

**Comment by helgatheviking** [comment]
@Mathib96 I could hack this out for $125. Let me know if that works for you.

**Comment by Mathib96** [comment]
Hi Helga. Do you have an fb account or skype. So we could disquss this further? :)

Hope you had a great new year!

//mathi

**Comment by helgatheviking** [comment]
You can reach me at http://www.kathyisawesome.com/contact

**Comment by Mathib96** [comment]
Hi Kate.

Seems like im going to need a "little" bit of help, with this kind of 
project.
What im trying to achieve is to have the subtitle fully integrated into 
Woocommerce.
That will include, archive listing, product pages, checkout flow, 
backend, emails etc.

Then what could be nice to have, is to have the ability in this kind of 
plugin, for setting the subtitle to be displayed before the title it self.

Backend:
Titel
Subtitle

Frontend.
Subtitle
Titel
Price
etc
etc
etc

Let me know what this would cost, and how long it would take. Keep in 
mind that i want this to have the ability to use the plugin on multiple 
sites, therefore
it needs to be developed into the plugin itself.

//Sincerly
Mathias Brask


Med venlig hilsen
*Mathias Brask*
CEO & Founder

*Bravo Computing IVS*
*Telefon:* +45 41 44 19 31
*E-mail:* mb@bravocom.dk <mailto:mb@bravocom.dk>

Bravo Computing - Vi gør IT-livet nemmere for dig! 
<http://bravocom.dk/profil.html#mathias>
Den 03-01-2016 kl. 23:37 skrev Kathy:
> You can reach me at http://www.kathyisawesome.com/contact
